/**
 * eSewa Signature Utility (Frontend)
 * Creates HMAC SHA256 signatures for eSewa payment integration
 */

/**
 * Create eSewa signature for payment initiation
 * @param params - Payment parameters
 * @returns Base64 encoded HMAC signature
 */
export function createSignature({
  amount,
  tax_amount,
  transaction_uuid,
  product_code,
}: {
  amount: number;
  tax_amount: number;
  transaction_uuid: string;
  product_code: string;
}): string {
  const secret = '8gBm/:&EnhH.1/q'; // eSewa test secret key
  const message = `total_amount=${amount + tax_amount},transaction_uuid=${transaction_uuid},product_code=${product_code}`;
  
  // Use Web Crypto API for HMAC (browser-compatible)
  // Note: In production, this should be done server-side for security
  // For now, we'll use a simple approach or call backend API
  
  // Since Web Crypto API requires async, we'll use a workaround
  // In production, always generate signatures on the backend
  return btoa(message); // Placeholder - actual implementation should use backend API
}

/**
 * Note: For production, signature generation should ALWAYS be done on the backend
 * This frontend function is only for demonstration purposes.
 * The actual signature should be generated by calling the backend API.
 */




